In [11]:
import pandas as pd
df = pd.read_csv("Metadata_Indicator_API_AFG_DS2_en_csv_v2_3436225.csv")
df.to_json("Metadata_json")

In [12]:
df = pd.read_json("Metadata_json.json")

In [14]:
import requests
import io
import pandas as pd

# URL for the World Bank API data for Afghanistan
url = "https://api.worldbank.org/v2/en/country/AFG?downloadformat=csv"

# Send a GET request to the URL
response = requests.get(url)

# Check if the request was successful
if response.status_code == 200:
    # Read the content of the response
    content = response.content
    
    # Use StringIO to create a file-like object from the content
    csv_file = io.StringIO(content.decode('utf-8'))
    
    # Read the CSV data into a pandas DataFrame
    df_afghanistan = pd.read_csv(csv_file)
    
    # Display the first few rows of the dataframe
    print(df_afghanistan.head())
else:
    print(f"Failed to retrieve data. Status code: {response.status_code}")

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xaf in position 14: invalid start byte

In [18]:
import pandas as pd

# Read the CSV file, skipping the first 4 rows and using '","' as the separator
df = pd.read_csv("API_AFG_DS2_en_csv_v2_3436225.csv", 
                 skiprows=4, 
                 sep='","',
                 engine='python',
                 quotechar='"',
                 na_values=[''])

# Clean up column names
df.columns = df.columns.str.replace('"', '')

# Display the first few rows of the dataframe
df.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,"2023,"
0,"""Afghanistan",AFG,"Intentional homicides, female (per 100,000 fem...",VC.IHR.PSRC.FE.P5,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.439053,1.274152,NaN,NaN,NaN,""","
1,"""Afghanistan",AFG,Battle-related deaths (number of people),VC.BTL.DETH,NaN,NaN,NaN,NaN,NaN,NaN,...,12284.000000,17278.000000,17985.000000,19014.000000,25676.000000,29940.000000,20475.000000,35787.000000,899.000000,""","
2,"""Afghanistan",AFG,Voice and Accountability: Percentile Rank,VA.PER.RNK,NaN,NaN,NaN,NaN,NaN,NaN,...,16.256157,18.719212,20.689655,22.167488,20.388350,21.256039,19.806763,7.246377,2.415459,""","
3,"""Afghanistan",AFG,Transport services (% of commercial service ex...,TX.VAL.TRAN.ZS.WT,NaN,NaN,NaN,NaN,NaN,NaN,...,15.432364,12.129803,22.705963,32.758449,29.167851,21.120967,14.490510,NaN,NaN,""","
4,"""Afghanistan",AFG,"Computer, communications and other services (%...",TX.VAL.OTHR.ZS.WT,NaN,NaN,NaN,NaN,NaN,NaN,...,63.230612,69.922852,61.682080,64.757064,65.516134,63.715220,74.273033,NaN,NaN,""","